### ISSUE TITLE
Too many figures opened

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#120]
I add this warning when I tested a case with 10 scenarios:

    /home/eric/dev/distributed-learning-contributivity/fl_training.py:389: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (matplotlib.pyplot.figure) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam figure.max_open_warning).

@RomainGoussault you might be the one the most familiar with this, should we do something or is it OK?

**Comment by RomainGoussault** [comment]
We can close the figures after saving them with `plt.close()`
