### ISSUE TITLE
Amount_per_partner is used twice in the results csv file 

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#126]
Here: https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/d9727913fd41d7ab1bd4d5e84a00a9f035f30445/scenario.py#L396             
And here: https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/d9727913fd41d7ab1bd4d5e84a00a9f035f30445/scenario.py#L416

The first one is a list of the fractions of dataset used by each partner. --> maybe we should rename it to something like `dataset_fraction_per_partner`.
The second one is a float corresponding to the actual fraction of dataset used by the partner.

**Comment by bowni** [comment]
Why do you think this is a bug? The second one is part of the parameters specific to the partner for which a line is written down. What did you have in mind that we should update/improve?

**Comment by RomainGoussault** [comment]
Ok when I wrote the issue I did NOT notice there was one amount with an S and one without an S..

Anyway, even without my sloppy reading, I think this is can be confusing when analysing the result file. 
But I guess this is not as urgent as I thought it was :)
