### ISSUE TITLE
Results.csv file is not populated with data when there is no contributivity method specified

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#130]
This happens because the every line of the dataframe is linked with a specific contributivity estimation:

https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/e5d86635bbc07d3a55ea078771c5fb4870901b1d/scenario.py#L483

**Comment by bowni** [comment]
Ok, fixed in #129
