### ISSUE TITLE
All scenario should be "validated" before starting any computation

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#132]
When running multiple scenarios, the scenarios are run one by one. If one fails, we will only know when it is running --> We should know at the very start of the program.

**Comment by bowni** [comment]
Ok, very good idea. What would be a Pythonic approach to that? @natct10 @RomainGoussault 

- regroup somewhere together all asserts applicable to a scenario ?
- then loop over scenarios, apply all asserts, and kick out scenarios that fail?
- or create a function like `assert_scenario()` that does that?

**Comment by natct10** [comment]
Hi, I like the idea of having a `assert_scenario` method *before* looping over each scenario!

**Comment by bowni** [comment]
- [ ] Add a verification that parameters are not duplicated in the config file
