### ISSUE TITLE
Refactor fl_training

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#134]
fl_training module should probably be a class. This would make the code more readable.

**Comment by bowni** [comment]
Ok, I'll work on that. Could you please @RomainGoussault provide a few recommendations about:

- what public vs. private attributes for this class?
- shoud we use the `property()` approach for certain attributes?
- what class methods vs. not-class methods?

I'll need to learn quite a lot on Python Classes best practices here...

**Comment by RomainGoussault** [comment]
@natct10 feel free to join this conversation. (I have much more experience in Java OOP than in Python OOP !)

- I would keep everything public for now
- For the property I don't see where we would need it
- I think we will only need instance methods since all the methods in fl_training need some scenario / or model  as parameters. This [article ](https://realpython.com/instance-class-and-static-methods-demystified/)sums up nicely the difference between Instance, Class, and Static Methods 
- I would move out methods that non-related to training to another module. For instance this one: https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/2784ff48820ebedd6e7a8194d080bbdaf9106fbf/fl_training.py#L27
