### ISSUE TITLE
Save the weights instead of the models

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#135]
While working on #131 I thought that we could save only the weights of the models instead of the models themselves in `model_list`. The reason we save them is to later extract their weights for aggregation purposes. So it doesn't seem optimal. What do you think @RomainGoussault ?

**Comment by RomainGoussault** [comment]
Yes I agree, if we are only aggregating the weights there is no point saving the model itself. Good point !
