### ISSUE TITLE
Add one or several other Keras' datasets

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#139]
For datasets already part of `keras.datasets` it seems that we could just add a config parameter, and corresponding switches in `Scenario` (check that the config parameter corresponds to a dataset part of the ones we cover) and `utils` (with a dedicated model architecture for each dataset we cover). See for example [Keras use case with CIFAR-10](https://keras.io/examples/cifar10_cnn/). What do you think @RomainGoussault ?
(this could be a first step prior to going further, with making the model architecture a user input, looking into Tensorflow datasets, etc.)

**Comment by RomainGoussault** [comment]
Yes I agree.
As you said we should start with one (hard-coded) model per data-set for now.
