### ISSUE TITLE
Clear_session for seq approach

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#142]
We should be able to call clear_session() even for the 'seq' approach

https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/bdd6ad02f042b3f98ffa96796155c1adcf6cb585/fl_training.py#L501

**Comment by natct10** [comment]
Seems to be interesting: https://github.com/keras-team/keras/issues/9379#issuecomment-455392681
