### ISSUE TITLE
Initialize model with model from a previous coalition?

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#144]
This could "save" a few epochs.

**Comment by celinejacques** [comment]
Indeed, it could save a few epochs and it could be very interesting in term of performances. In the other hand, I wonder how contributivity score could be impacted. 

For example, we train a model on three partners with a federated approach. Then we want to add a partner and train a model on these 4 partners. If we use the model trained on the 3 partners to initialize the model for the 4 partners, isn't there a risk that the contributivity score might be biased? \
I mean, in an extreme example, let's assume that the data from the 4th partner are totally new. This dataset should bring more information to the model than the three others. 

What do you think? Obviously we can do some experiments to illustrate this intuition. @bowni @RomainGoussault @Thomas-Galtier @jeromechambost

**Comment by Thomas-Galtier** [comment]
Yes there is a risk that the optimisation of the loss would be trapped in a local minimum after being initialized like this.
