### ISSUE TITLE
Create "portfolio" of past experiments

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#146]
Possibilities:

- notebook (with or without binder)
- wiki
- ?

**Comment by natct10** [comment]
I was also thinking about https://osf.io/ to publish some results we would like to publish with a DOI (citation reference) and in a metedata harvestable format. What do you think about it?

**Comment by natct10** [comment]
> I was also thinking about https://osf.io/ to publish some results with a DOI (citation reference) and in a metedata harvestable format. What do you think about it?

Osf is fire! cc @bowni
