### ISSUE TITLE
Add model ensembling/blending approaches (mpl + contributivity)

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#148]
Some time ago we had discussed with @camillemarini another approach to contributivity that would be based on a model ensembling/blending approach to multi-partner learning (should we say ensembling or blending?).
The idea would be to transpose Shapley to it, the characteristic function would be much cheaper computationnally:
- an independent model is trained **once** on each dataset providing partner
- different ensembling/blending on different coalitions of **models** are done, with a perf. evaluation
@Thomas-Galtier what do you think?
cc @RomainGoussault @celinejacques @jeromechambost @natct10

**Comment by Thomas-Galtier** [comment]
It seems like a good idea. @camillemarini do you have some documentation on model ensembling? I am not familiar with these approaches.

**Comment by RomainGoussault** [comment]
Interesting idea ! This could be indeed much faster.

**Comment by bowni** [comment]
@Thomas-Galtier does that help https://towardsdatascience.com/simple-guide-for-ensemble-learning-methods-d87cc68705a2 ?
