### ISSUE TITLE
Weighted weights averaging ?

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#15]
If nodes don"t have the same data size :
When aggregating models, we should probably not blindy take the mean of the weights of all nodes but we should take the weighted mean.

**Comment by RomainGoussault** [comment]
Agregating weights can be done in several ways:

- Averaging
- Weighted averaging depending on dataset size
- Weighted averaging depending on incremental performance


https://blog.acolyer.org/2019/08/19/robust-learning-from-untrusted-sources/

**Comment by bowni** [comment]
> Agregating weights can be done in several ways:
> 
> * Averaging
> * Weighted averaging depending on dataset size
> * Weighted averaging depending on incremental performance
> 
> https://blog.acolyer.org/2019/08/19/robust-learning-from-untrusted-sources/

I think we should try to parameterize the way the aggregation is weighted. This could be done maybe with:
- different weighting methods that would return a vector of weights
- a parameter to designate with approach is chosen for a given scenario
- passing this parameter as argument to the FL function
- having the FL function call the appropriate weighting methods to get the weights

What do you think @RomainGoussault @celinejacques @Thomas-Galtier?

**Comment by bowni** [comment]
Done in PR #80
