### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#150]
A few ideas:

- [x] Indicate that issues with tag "help wanted" could be picked up by new people
- [x] Add indication of Slack channel relevant for this project
- [x] Add invite to student projects
- [x] Add Substra new logo

**Comment by RomainGoussault** [comment]
- [ ] Add link to one or two interesting experiments

**Comment by bowni** [comment]
> * [ ]  Add link to one or two interesting experiments

Super idea @RomainGoussault , but could you do it in the PR and the branch where you'll add the first saved experiment on catastrophic forgetting?

So that we can merge this one quickly and have that section about interaction with the project.
