### ISSUE TITLE
For fedavg the very first model sent to the nodes should be the same for all nodes

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#169]

**Comment by bowni** [comment]
I did that already under the umbrella of the dataset refactoring PR, see https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/e5ca82f641b32aa7d61199875b09c8fa0a099864/multi_partner_learning.py#L459 where now a model is generated and then deep-copied for each partner.

**Comment by bowni** [comment]
I let you close it @RomainGoussault if that convinces you :)

**Comment by RomainGoussault** [comment]
Ah yes you are right @bowni  :)
