### ISSUE TITLE
Update to pandas 1.X

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#171]
This is needed for google collab --> https://github.com/SubstraFoundation/distributed-learning-contributivity/pull/164#issuecomment-646052648

cc @natct10

**Comment by natct10** [comment]
Okay, thank you Romain! Have you already tested 1.x versions of pandas?

**Comment by RomainGoussault** [comment]
> Okay, thank you Romain! Have you already tested 1.x versions of pandas?

no
