### ISSUE TITLE
Another way to aggregate model in fedavg

### ISSUE THREAD

**Issue by Thomas-Galtier** [SubstraFoundation/distributed-learning-contributivity#173]
I find [this article](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9006327&casa_token=flGOJ2riZyoAAAAA:zm-CFCHyg9XcAnyrhjYhmRBLwPI35r6eGikt7180j08TPgELNw1ZEClPsojT9zzKasXlWWLQcw&tag=1) where they use a different way to average the model in parallel federated learning. It would be interesting to test it.

**Comment by Thomas-Galtier** [comment]
Here is the pdf version of the article [Song 2019.pdf](https://github.com/SubstraFoundation/distributed-learning-contributivity/files/4819210/Song.2019.pdf)

**Comment by bowni** [comment]
This is indeed very interesting, as we discussed at our last workgroup meeting, well spotted Thomas!

**Comment by bowni** [comment]
Two aspects:

1. Aggregation of gradients (not weights)
1. Within a multi-partner training and the x100 iterations, variate the subcoalitions used

**Comment by Thomas-Galtier** [comment]
closing this issue as it is similar to issue #177
