### ISSUE TITLE
More tests of the config.yml: unkown parameters

### ISSUE THREAD

**Issue by GauthierGar** [SubstraFoundation/distributed-learning-contributivity#184]
https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/3414c86ec432abf79ead3334ec101a74a1999f9a/config_quick_debug.yml#L19-L20

If the user makes a mistake, writing `gradit_updates_per_pass_count:` the parameter can't be used in the computation, the model is then trained using the default parameter `constants.DEFAULT_GRADIENT_UPDATES_PER_PASS_COUNT` 8
It's unlikely the user understands that the model wasn't trained with the specified parameter: It's just write in the result.csv

To prevent the user making this kind of mistake, I suggest we raise an error if there are unrecognized parameters in the .yml
or maybe warn the user when default parameters are used.

**Comment by RomainGoussault** [comment]
Totally agree to raise an error in this case !

**Comment by bowni** [comment]
Agree too, this would be a nice addition.
