### ISSUE TITLE
Unused argument and functions in dataset.py

### ISSUE THREAD

**Issue by GauthierGar** [SubstraFoundation/distributed-learning-contributivity#187]
https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/3414c86ec432abf79ead3334ec101a74a1999f9a/dataset.py#L38-L48

These 2 functions are never used/called in the whole repo, we maybe should removed them

https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/3414c86ec432abf79ead3334ec101a74a1999f9a/dataset.py#L25
this is why the user has to create a variable `input_shape` in datasets/dataset_xx.py 
this attribute seems to stay unused, we could removed it

**Comment by GauthierGar** [comment]
I wrote a mistake, the function `train_val_split` is used in `scenario.py`, `preprocess_labels` is stil unused.
https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/3414c86ec432abf79ead3334ec101a74a1999f9a/dataset.py#L38-L42

In `scenario.py`, the training data are often split (in 2 times) with `train_test_split(self.x_train, self.y_train, test_size=0.2, random_state=42)` to obtain test and validation data:
https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/3414c86ec432abf79ead3334ec101a74a1999f9a/scenario.py#L471-L476

We could improve the readibility by replacing all these lines with a call to `dataset.train_val_split`

**Comment by bowni** [comment]
This is now obsolete - closing it
