### ISSUE TITLE
Unit Testing new script to generate strandard scenario

### ISSUE THREAD

**Issue by GauthierGar** [SubstraFoundation/distributed-learning-contributivity#191]
To test all the functions of the projects, we could create a script that will generate a list of scenario,
based on the datasets and federated learning approaches currenty supported.
This list would be used as arguments in `tests.py` to test more complex functions such as split_data (Functions that need `scenario` `mpl` `dataset` objects as arguments)

**Comment by bowni** [comment]
Obsolete
