### ISSUE TITLE
Update notebooks with new dataframe columns names

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#194]
The result dataframe has new columns names (samples_split_description instead of samples_split_options, dataset_fraction_per_partner insteadd of amounts_per_partner_list, etc).

We should update the notebooks to be able to read these new columns names.

**Comment by bowni** [comment]
I think this is obsolete, isn't it? Can you confirm @RomainGoussault @arthurPignet ?

**Comment by arthurPignet** [comment]
I think that this issue referres to the old_examples_of_results_analysis notebooks so it is not really obsolete.

**Comment by arthurPignet** [comment]
I tried to update these notebook but they are really obsolete. It will be better to rewrite completely the notebooks. 

I suggest to remove the old notebooks, and to create a new tutorial notebook, which shows how to use an experiment object, to reproduce the figures in these old notebooks

**Comment by arthurPignet** [comment]
The notebooks are to be replaced by tutorial 4 - running expriment demo
