### ISSUE TITLE
Try/except fetch datasets

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/distributed-learning-contributivity#206]
In order to avoid Travis issues when cifar provider is not reachable, we could try/except to get the dataset and use a local copy when KO. 
See discussion [here](https://github.com/SubstraFoundation/distributed-learning-contributivity/commit/e6007adfece5111b493c22e35fa6af04571a4966#commitcomment-41525683)

**Comment by aygalic** [comment]
Have the same issue in some #205 deploy

**Comment by bowni** [comment]
I think that is a good idea.

**Comment by natct10** [comment]
Same for titanic dataset!

**Comment by bowni** [comment]
@arthurPignet I add this one to you, same theme you've been working on to improve the dataset loading part.

**Comment by arthurPignet** [comment]
After digging a bit into keras, it already stores cifar10 locally, so keras downloads the dataset only if it did not find cifar in the cache. For me there is two solutions, catch the error raised by the URLerror and HTTPerror, and maybe retry 3 or 5 times or put the dataset into the repo (which is quite heavy)
