### ISSUE TITLE
Typo in mpl_with_losses.ipynb

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/distributed-learning-contributivity#207]
Getting trouble with `root_folder = exp_path = Path().absolute()..parent / "experiments"` in the `mpl_with_losses` notebook, in the first cell

**Comment by akshaysonawaneS** [comment]
is this issue solved?

**Comment by natct10** [comment]
Hi @akshaysonawaneS, thank you for your interest! 
I don't think that it had already been addressed, would you be interested in fixing this `path` issue?

**Comment by akshaysonawaneS** [comment]
Yes please

**Comment by natct10** [comment]
Oh that's great! Please feel free to raise any question!

**Comment by natct10** [comment]
The [notebook](https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/master/notebooks/mpl_with_losses.ipynb) is located in `distributed-learning-contributivity/notebooks/mlp_with_losses.ipynb`

**Comment by akshaysonawaneS** [comment]
What does you exactly want in root_path?

**Comment by bowni** [comment]
It has to point to `<project directory>/experiments`, but I let @RomainGoussault who initiated the notebooks and the `/experiments` folder (which, btw, is gitignored).

**Comment by RomainGoussault** [comment]
Hello, I think there are 2 problems:

- A typo, there should be only one dot between `absolute()` and `parent` in `Path().absolute()..parent`
- The variable `exp_path  `is never used elsewere, we should remove it (and keep `root_folder`)

**Comment by bowni** [comment]
By the way @akshaysonawaneS can you let us know how you found out about this project? It would be interesting for us to know! In any case: WELCOME 😃

**Comment by akshaysonawaneS** [comment]
I found about this project from [https://goodfirstissue.dev/](good first issue)

**Comment by akshaysonawaneS** [comment]
-[good first issue](https://goodfirstissue.dev/)

**Comment by akshaysonawaneS** [comment]
I found this about project from [good first issue](https://goodfirstissue.dev/)
