### ISSUE TITLE
Remove some print()

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#21]
The standart ouput is bit cluttered with many many print()
We should remove some.

The main idea is to be able to have an idea about the progression of the computation. Ideally have some percentage.

**Comment by bowni** [comment]
The main source of prints is the `verbose=1` in the algo training I think. We could make it a parameter in `my_scenario`. What do you think about it @RomainGoussault ?

**Comment by RomainGoussault** [comment]
Yes, good point
