### ISSUE TITLE
[feature-request] Add a gitpage

### ISSUE THREAD

**Issue by natct10** [SubstraFoundation/distributed-learning-contributivity#211]
What about displaying the README on a fresh github page?

**Comment by natct10** [comment]
Sounds good or not? It could be nice to render the package documentation? @bowni @RomainGoussault please let me know if so, otherwise I close this feature request.

**Comment by bowni** [comment]
I don't remember: how would it look to have the README rendered as a gitpage?
I am not too sure it would present a real benefit vs. the current rendering, which enables navigating easily with the links included in the README, would it @natct10?

**Comment by natct10** [comment]
There are several templates that offer great layout, but I am not sure that it would add any other real benefit, so let's close this issue.
