### ISSUE TITLE
[feature-request] Package : Improve/replace samples_split_option : 'advanced'

### ISSUE THREAD

**Issue by aygalic** [SubstraFoundation/distributed-learning-contributivity#217]
The advanced methods of spliting dataset are not intuitive for a package use.

Being able to manually create partner via a `Partner` class and assignate `dataset` object would make sense in my opinion.

This can open a way for remote dataset usage and federated learning run between different actual partners.

**Comment by arthurPignet** [comment]
I would suggest to create a `Splitter` object. In the init parameter we would specified the 'advanced' type of parameter.
Two other classes would inherit from Splitter, RandomSplitter (actual 'random' config) and StratifiedSplitter. 
Its would implement a method which take a dataset and a partner list as parameters, and split the data
