### ISSUE TITLE
Logs are not shown when running test

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#254]
When running the test with pytest, the logs are not shown.

**Comment by arthurPignet** [comment]
I wonder if it is really an issue. 
The log of pytest would became totally unreadable don't you think ?

**Comment by RomainGoussault** [comment]
Yes you are right. 
I think my use case when I opened this issue was being able to see the logs when writing the tests. Is there some king of argument to pytest to be able to see the logs ?

**Comment by arthurPignet** [comment]
Pytest shows the log captured when there is a bug, or a test failed

I don’t think you can see the log is everything run well. Maybe with -vv ? I saw that somewhere.
However I think that you could test your tests Without pytest ? In a notebook, or in a small script 

Arthur Pignet

**Comment by arthurPignet** [comment]
I think we can close the issue in that case, the library does'nt need any change ?
