### ISSUE TITLE
Launch simulations on the full MNIST dataset

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#28]
Define first interesting scenarios to simulate:
1. Same volumes + Random data split
2. Same volumes + Stratified data split
3. Different volumes + Random data split
4. Different volumes + Stratified data split

@RomainGoussault can you find out a good way to store / make reproducible those scenarios?

**Comment by RomainGoussault** [comment]
[results_summary.txt](https://github.com/SubstraFoundation/distributed-learning-contributivity/files/3916160/results_summary.txt)
