### ISSUE TITLE
Approximation of amounts_per_partner

### ISSUE THREAD

**Issue by kat-leen** [SubstraFoundation/distributed-learning-contributivity#341]
When attributing an infinite fraction to the amounts_per_partner parameter, the rounding is not very close to the true value and the sum is not always equal to 1. 

For example: `amounts_per_partner=[0.8/9.0]*9 + [0.1]*2`
returns:
`Partners' relative number of samples : [0.09, 0.09, 0.09, 0.09, 0.09, 0.09, 0.09, 0.09, 0.09, 0.1, 0.1] (versus initially configured: [0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.08888888888888889, 0.1, 0.1])`
The fractions sums up to 1.01.

**Comment by kat-leen** [comment]
Thank you @bowni for both explanations.

Should we not merge the `StratifiedSplitter` and the `AdvancedSplitter` using only the `samples_split_configuration` of the `AdvancedSplitter` for inferring the `amounts_per_partner`?

**Comment by bowni** [comment]
Yes we could this would already be better 😃 However `AdvancedSplitter` is quite complex, and is itself a specific case of the most generic `FlexibleSplitter`. Thus I believe that if we engage into rewriting some splitters, we should rewrite them as using `FlexibleSplitter`.
