### ISSUE TITLE
Review model evaluation

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#35]
@bowni  this looks weird:
https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/master/fl_training.py#L166

We always evaluate the model on the last node

**Comment by RomainGoussault** [comment]
One more thing to do : correct early stopping so it uses validation data and not test data. Actually validation data should not be used per node but only per scenario to do early stopping.

**Comment by bowni** [comment]
See PR #43
