### ISSUE TITLE
Unable to run single partner learning approach

### ISSUE THREAD

**Issue by HeytemBou** [SubstraFoundation/distributed-learning-contributivity#351]
https://github.com/SubstraFoundation/distributed-learning-contributivity/blob/4fb247a35ae40ce27790b888cc6e4cb52134fa68/mplc/multi_partner_learning/basic_mpl.py#L350

@arthurPignet Is this comment still valid or is it no longer possible to use the Single Partner Learning approach when running a scenario?

**Comment by arthurPignet** [comment]
I just checked, the mpl method single partner learning does exist, (in basic mpl) but it is not reachable. I will fix it. 
However this comment is not really relevant anymore, the method raises an error if only one partner is provided, and doesn't fall back to the dedicated single partner class
