### ISSUE TITLE
to aggregate the models fitted on the nodes or to merge the nodes before fitting

### ISSUE THREAD

**Issue by Thomas-Galtier** [SubstraFoundation/distributed-learning-contributivity#36]
In the function "compute_test_score" in the "fl_learning.py" file,  I understand that we average the coefficients of the models fitted on each node. Am I right?

Shouldn't we rather merge the node's datasets and then fit a model on the merged datasets?

**Comment by RomainGoussault** [comment]
Yes you understand correctly.

But we can NOT merge the nodes dataset because we don't want to move the data. Every dataset should stay on its node.

**Comment by Thomas-Galtier** [comment]
Ok thank you for the clarification. I understand we aggregate to avoid moving the data, thought I am very surprised by this aggregation method. Indeed, with the MNIST dataset the aggregation of  nodes tends to lower the accuracy... I would have expected an aggregated model to be stronger than a model trained on a single node.

**Comment by bowni** [comment]
To me, intuitively:
- training on the whole MNIST dataset > training on the whole dataset split into independent nodes
- training on a 10th of the whole dataset < training on the whole dataset split into independent nodes
Do you share this intuition?
