### ISSUE TITLE
Study SHAP to see if there are interesting Shapley approximation algos

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#38]

**Comment by bowni** [comment]
https://github.com/slundberg/shap

**Comment by Thomas-Galtier** [comment]
I  read paper 6 which refer to [this paper](https://www.researchgate.net/profile/Stan_Lipovetsky/publication/262837124_Modern_Marketing_Research_Combinatorial_Computations_Shapley_Value_versus_TURF_tools/links/5548f7a40cf25a87816aad3f/Modern-Marketing-Research-Combinatorial-Computations-Shapley-Value-versus-TURF-tools.pdf)  If I understand right they propose a computation by stratification similar to what is proposed in this [other paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7101858)

**Comment by Thomas-Galtier** [comment]
paper 5 suggest using monte-carlo sampling
