### ISSUE TITLE
Perform a simulation

### ISSUE THREAD

**Issue by bowni** [SubstraFoundation/distributed-learning-contributivity#40]
4 scenarios we want test :
- 2 splits of data: stratified vs. random
- volume: same volume per node vs. different volumes
--> 4 scenarios

3 contributivity measures: Shapley, Truncated Monte Carlo Shapley, independent contributivities.

**Comment by bowni** [comment]
Description of the 4 scenarios to simulate, with 4 nodes each:

|  | **Randomized** | **Stratified** |
|---|---|---|
| **Equal volumes** | 25% each, randomized split | 25% each, stratified split  |
| **Different volumes** | volumes 10% 15% 30% 45%, randomized split  | volumes 10% 15% 30% 45%, stratified split |

**Comment by bowni** [comment]
Suggestion Thomas: add a dataset with a lot of corrupted data, to see if our measurements gives it a bad contributivity value.

**Comment by bowni** [comment]
@RomainGoussault to re-launch TMCS, relax parameters: `sv_accuracy = 0.01`, `alpha = 0.9`, `contrib_accuracy = 0.5`

**Comment by RomainGoussault** [comment]
Results with the TMC. 
TMC parameters were NOT relaxed.
[TMC_results.zip](https://github.com/SubstraFoundation/distributed-learning-contributivity/files/4219054/TMC_results.zip)
