### ISSUE TITLE
interesting lead

### ISSUE THREAD

**Issue by mattthieu** [SubstraFoundation/distributed-learning-contributivity#44]
Hello, yesterday I talked to http://azer.bestavros.net/ who told me he had had a PhD student who worked on building shapley value estimators. Probably interesting to dig deeper... :-) Cheers

**Comment by bowni** [comment]
Thanks @mattthieu, definitely we should look into that!

**Comment by Thomas-Galtier** [comment]
I contacted him this morning, I am waiting for his response

**Comment by Thomas-Galtier** [comment]
I checked the paper of his student but unfortunately they only used a Monte-Carlo approach.
