### ISSUE TITLE
Compute the contributivity of the model

### ISSUE THREAD

**Issue by Thomas-Galtier** [SubstraFoundation/distributed-learning-contributivity#45]
See the attached file.
 
[Issue_Contrib_du_model(2).pdf](https://github.com/SubstraFoundation/distributed-learning-contributivity/files/4091955/Issue_Contrib_du_model.2.pdf)

**Comment by bowni** [comment]
We could also consider taking into account the starting state model?

**Comment by Thomas-Galtier** [comment]
new version
[Issue_Contrib_du_model(4).pdf](https://github.com/SubstraFoundation/distributed-learning-contributivity/files/4160115/Issue_Contrib_du_model.4.pdf)
