### ISSUE TITLE
Implement easier to handle input and output of simulations

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#47]
- Inputs (scenario) are written in the `simulation_run` file. We could have a config file (YAML) to easily wrote the different scenarii we want to run.
- Outputs are written in a report file, one for each scenario. For many scenarri it will be a pain to have a grasp of all the results. We could have ONE dataframe that sums up all the results in single object. And then writes it as a cvs for easy parsing.

Based on experience lauchning simulations #46

**Comment by bowni** [comment]
Totally agree that would be a handy improvement. I'ad add a third item:

- [ ] Give a name or id to each scenario and reflect it in the results' folder/file name
