### ISSUE TITLE
Add normalized contributivity in reports

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#55]

**Comment by bowni** [comment]
@RomainGoussault I noticed from the results you shared earlier today that you added the normalization already. I think it is important to add comments to explain how to interpret the contributivity values:

- by construction Shapley values sums up to the _score_ of the complete coalition of _players_
- when normalized it becomes more additive percentages

**Comment by RomainGoussault** [comment]
@Thomas-Galtier wrote it :)
