### ISSUE TITLE
Add param to choose between parallel or sequential federated learning

### ISSUE THREAD

**Issue by RomainGoussault** [SubstraFoundation/distributed-learning-contributivity#91]
From the Substra whitepaper: 
![image](https://user-images.githubusercontent.com/5354301/78224177-56fe2980-74c8-11ea-85b3-f53491d20e11.png)
We now only do parallel FL, we could a param to do sequential FL.

**Comment by bowni** [comment]
Distributed learning approaches we could add:

- sequential: in which case there is no aggregation at the end of a mini-batch
- mix: sequential with an aggregation

**Comment by bowni** [comment]
Here are descriptive schemas:

1. Parallel + aggregation
[Editable here](https://docs.google.com/drawings/d/1r3GX8_M3spMOaXmV0dyENzCTYJ-bqLWo7IKWd1opxk0/edit?usp=sharing)

![collab_rounds_parallel_agg](https://user-images.githubusercontent.com/2467672/80227344-c8577500-864d-11ea-84c6-aa7bf8c7fef3.png)


1. Sequential
[Editable here](https://docs.google.com/drawings/d/1zzf_aOwV4TyhSYpe7JvgqaOHCxYREUXZOkW5d4wvSBA/edit?usp=sharing)

![collab_rounds_sequential](https://user-images.githubusercontent.com/2467672/80227364-ce4d5600-864d-11ea-925b-6d2e1cc237bb.png)


1. Sequential + aggregation
[Editable here](https://docs.google.com/drawings/d/1V0mV5aiyxPYI15ELbWu5SEzlRtofq6wbmfslQeZ8kZU/edit?usp=sharing)

![collab_rounds_sequential_agg](https://user-images.githubusercontent.com/2467672/80227377-d3aaa080-864d-11ea-906e-dd9bb3d27a43.png)

**Comment by bowni** [comment]
Notes:

- In the sequential, there is a strong dependency on the quality / representativity of the last mini-batch. We could take the best of the last 5 ones or something like that
- Maybe store the sequence (since it is shuffled)

**Comment by natct10** [comment]
> Here are descriptive schemas:
> 
>     1. Parallel + aggregation
>        [Editable here](https://docs.google.com/drawings/d/1r3GX8_M3spMOaXmV0dyENzCTYJ-bqLWo7IKWd1opxk0/edit?usp=sharing)
> 
> 
> ![collab_rounds_parallel_agg](https://user-images.githubusercontent.com/2467672/80227344-c8577500-864d-11ea-84c6-aa7bf8c7fef3.png)
> 
>     1. Sequential
>        [Editable here](https://docs.google.com/drawings/d/1zzf_aOwV4TyhSYpe7JvgqaOHCxYREUXZOkW5d4wvSBA/edit?usp=sharing)
> 
> 
> ![collab_rounds_sequential](https://user-images.githubusercontent.com/2467672/80227364-ce4d5600-864d-11ea-925b-6d2e1cc237bb.png)
> 
>     1. Sequential + aggregation
>        [Editable here](https://docs.google.com/drawings/d/1V0mV5aiyxPYI15ELbWu5SEzlRtofq6wbmfslQeZ8kZU/edit?usp=sharing)
> 
> 
> ![collab_rounds_sequential_agg](https://user-images.githubusercontent.com/2467672/80227377-d3aaa080-864d-11ea-906e-dd9bb3d27a43.png)

This looks so neat, well done sir!
